max_text_chars: 64
item_shop:
  price_text: "ยง7Price: "
  seller_text: "ยง7Seller: "
  misc_lore:
  - "ยง7Right click to buy 1"
  - "ยง7Shift + Right click to buy all"
  - ""
  - "Owner: Click to cancel"
log: true

