main: com.ar.askgaming.bettershop.BetterShop
name: BetterShop
api-version: 1.21
version: 1
author: AMONLY
soft-depend: [Vault, RealisticEconomy]
commands:
  shop:
    description: Open the shop
    aliases: [bs, bshop]
  globalshop:
    description: Open the global shop
    aliases: [gshop, gbs]
  servershop:
    description: Open the server shop
    aliases: [sshop, sshop]
  auction:
    description: Open the auction
    aliases: [auc]
  trade:
    description: Open the trade
    aliases: [tr]