main: com.ar.askgaming.bettershop.BetterShop
name: BetterShop
api-version: 1.21
version: 1
author: AMONLY
soft-depend: [Vault, RealisticEconomy]
commands:
  shop:
    description: Open the shop
    aliases: [bs, bshop]