main: com.ar.askgaming.bettershop.BlockShop
name: BlockShop
api-version: 1.21
version: 1
author: AMONLY
soft-depend: [Vault, RealisticEconomy]
commands:
  shop:
    description: Open the shop
    aliases: [bs, bshop]